package com.link.entity;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : piapix.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PITIMESTAMP extends Structure {
	/** 1-12 */
	public int month;
	/** four digit */
	public int year;
	/** 1-31 */
	public int day;
	/** 0-23 */
	public int hour;
	/** 0-59 */
	public int minute;
	/** timezone information */
	public int tzinfo;
	/** 0-59.99999999.... */
	public double second;
	public PITIMESTAMP() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("month", "year", "day", "hour", "minute", "tzinfo", "second");
	}
	/**
	 * @param month 1-12<br>
	 * @param year four digit<br>
	 * @param day 1-31<br>
	 * @param hour 0-23<br>
	 * @param minute 0-59<br>
	 * @param tzinfo timezone information<br>
	 * @param second 0-59.99999999....
	 */
	public PITIMESTAMP(int month, int year, int day, int hour, int minute, int tzinfo, double second) {
		super();
		this.month = month;
		this.year = year;
		this.day = day;
		this.hour = hour;
		this.minute = minute;
		this.tzinfo = tzinfo;
		this.second = second;
	}
	public PITIMESTAMP(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PITIMESTAMP implements Structure.ByReference {
		
	};
	public static class ByValue extends PITIMESTAMP implements Structure.ByValue {
		
	};
}
